### ISSUE TITLE
Are there any builds?

### ISSUE THREAD

**Issue by Kreijstal** [umairsyed613/WinScreenKey#1]
to download it?

**Comment by umairsyed613** [comment]
here you can file the latest release build.
https://github.com/umairsyed613/WinScreenKey/tree/master/Src/ExecutableFile

**Comment by Kreijstal** [comment]
You should put it in github releases

**Comment by umairsyed613** [comment]
Here you go https://github.com/umairsyed613/WinScreenKey/releases/tag/1.0.0
