### ISSUE TITLE
Cannot  display ESC key

### ISSUE THREAD

**Issue by elicec** [umairsyed613/WinScreenKey#2]
If I  press  ESC ,it  show a [?]

**Comment by umairsyed613** [comment]
There are alot of the keys still not mapped, will try to spare some time for this soon 😊

**Comment by umairsyed613** [comment]
Released new version which will cover this
https://github.com/umairsyed613/WinScreenKey/releases/tag/1.1.0

**Comment by elicec** [comment]
thank  you very much
